//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// AUXEQ.rc で使用
//
#define IDC_MYICON                      2
#define IDD_AUXEQ_DIALOG                102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_AUXEQ                       107
#define IDI_SMALL                       108
#define IDC_AUXEQ                       109
#define IDR_MAINFRAME                   128
#define IDB_BMP_BLUE                    135
#define IDB_LIGHTBLUE                   138
#define IDB_BITMAP4                     142
#define IDB_BMP_GRAY                    146
#define IDB_BMP_GREEN                   147
#define IDB_BMP_LIGHTBLUE               148
#define IDB_BMP_MAGENTA                 149
#define IDB_BMP_RED                     151
#define IDB_BMP_WHITE                   153
#define IDB_BMP_YELLOW                  154
#define IDD_DIALOG_IMAGE_PROC           155
#define IDC_LIST1                       1000
#define IDC_TAB_TASKNAME                1001
#define IDC_STATIC_FUNCTION             1002
#define IDC_STATIC_ITEM                 1003
#define IDC_TASK_FUNC_RADIO1            1004
#define IDC_TASK_FUNC_RADIO2            1005
#define IDC_TASK_FUNC_RADIO3            1006
#define IDC_TASK_FUNC_RADIO4            1007
#define IDC_TASK_FUNC_RADIO5            1008
#define IDC_TASK_FUNC_RADIO6            1009
#define IDC_TASK_MON_CHECK1             1010
#define IDC_TASK_MON_CHECK2             1011
#define IDSET                           1012
#define IDRESET                         1013
#define IDC_STATIC_ITEM2                1014
#define IDC_TASK_MODE_RADIO0            1015
#define IDC_TASK_MODE_RADIO1            1016
#define IDC_TASK_MODE_RADIO2            1017
#define IDC_TASK_EDIT1                  1018
#define IDC_STATIC_ITEM3                1019
#define IDC_TASK_EDIT2                  1020
#define IDC_STATIC_ITEM4                1021
#define IDC_TASK_EDIT3                  1022
#define IDC_STATIC_ITEM5                1023
#define IDC_TASK_EDIT4                  1030
#define IDC_STATIC_ITEM6                1031
#define IDC_TASK_EDIT5                  1032
#define IDC_STATIC_ITEM7                1033
#define IDC_TASK_EDIT6                  1034
#define IDC_STATIC_ITEM8                1035
#define IDC_TASK_ITEM_CHECK1            1038
#define IDC_TASK_ITEM_CHECK2            1039
#define IDC_TASK_ITEM_CHECK3            1040
#define IDC_TASK_ITEM_CHECK4            1041
#define IDC_TASK_ITEM_CHECK5            1042
#define IDC_TASK_ITEM_CHECK6            1043
#define IDC_LIST                        2000
#define IDC_STATIC_TITLE_IMAGE          2000
#define IDC_STATIC_TASKNAME             2001
#define IDC_STATIC_TITLE_TAGET_POS      2002
#define IDC_STATIC_TARGET_1             2003
#define IDC_STATIC_TARGET_2             2004
#define IDC_STATIC_TITLE_SWAY_SENSOR_INFO 2005
#define IDC_STATIC_TITLE_TILT           2006
#define IDC_STATIC_TITLE_TILT_SPD       2007
#define IDC_STATIC_TITLE_H              2011
#define IDC_SLIDER_H1_LOW               2013
#define IDC_STATIC_TITLE_IMG_GRAB_TIME  2014
#define IDC_STATIC_VAL_H1_LOW           2015
#define IDC_SLIDER_H1_UPP               2016
#define IDC_STATIC_VAL_H1_UPP           2017
#define IDC_SLIDER_S1_LOW               2018
#define IDC_STATIC_TASKNAME_TITLE       2019
#define IDC_STATIC_TITLE_S              2019
#define IDC_STATIC_VAL_S1_LOW           2020
#define IDC_SLIDER_S1_UPP               2021
#define IDC_STATIC_VAL_S1_UPP           2022
#define IDC_SLIDER_V1_LOW               2023
#define IDC_STATIC_TITLE_V              2024
#define IDC_STATIC_VAL_V1_LOW           2025
#define IDC_SLIDER_V1_UPP               2026
#define IDC_STATIC_VAL_V1_UPP           2027
#define IDC_SLIDER_H2_LOW               2028
#define IDC_STATIC_VAL_H2_LOW           2030
#define IDC_STATIC_TITLE_IMAGE_STAT     2031
#define IDC_SLIDER_H2_UPP               2032
#define IDC_STATIC_VAL_H2_UPP           2033
#define IDC_SLIDER_S2_LOW               2034
#define IDC_STATIC_VAL_S2_LOW           2036
#define IDC_SLIDER_S2_UPP               2037
#define IDC_STATIC_VAL_S2_UPP           2038
#define IDC_SLIDER_V2_LOW               2039
#define IDC_STATIC_VAL_V2_LOW           2041
#define IDC_SLIDER_V2_UPP               2042
#define IDC_STATIC_VAL_V2_UPP           2043
#define IDC_STATIC_TITLE_NOISEFILTER    2046
#define IDC_SLIDER_NOISEFILTER1         2047
#define IDC_STATIC_VAL_NOISEFILTER1     2048
#define IDC_COMBO_NOISEFILTER1          2049
#define IDC_CHECK_CURSOR                2050
#define IDC_CHECK_ROI                   2051
#define IDC_COMBO_NOISEFILTER2          2052
#define IDC_COMBO_IMAGE                 2053
#define IDC_SLIDER_NOISEFILTER2         2054
#define IDC_STATIC_TITLE_CAMERA_EXPOSURE 2055
#define IDC_STATIC_VAL_NOISEFILTER2     2056
#define IDC_STATIC_TITLE_TILT_STAT      2058
#define IDC_SLIDER_CAMERA_EXPOSURE      2059
#define IDC_STATIC_VAL_CAMERA_EXPOSURE  2060
#define IDC_SLIDER_TARGET_LEN           2061
#define IDC_STATIC_TARGET_POS_X_1       2062
#define IDC_STATIC_TARGET_POS_X_2       2063
#define IDC_STATIC_TARGET_POS_Y_1       2064
#define IDC_STATIC_TARGET_POS_Y_2       2065
#define IDC_STATIC_TILT_DEG_X           2068
#define IDC_STATIC_TILT_DEG_Y           2069
#define IDC_STATIC_TILT_RAD_X           2070
#define IDC_STATIC_TILT_RAD_Y           2071
#define IDC_STATIC_IMG_GRAB_TIME        2072
#define IDC_STATIC_VAL_TARGET_LEN       2073
#define IDC_STATIC_IMAGE_STAT           2074
#define IDC_STATIC_TILT_STAT            2075
#define IDC_STATIC_TILT_SPD_DEG_X       2076
#define IDC_STATIC_TITLE_SWAY           2077
#define IDC_STATIC_SWAY_X               2078
#define IDC_STATIC_SWAY_Y               2079
#define IDC_STATIC_TITLE_SWAY_SPD       2080
#define IDC_STATIC_SWAY_SPD_X           2081
#define IDC_STATIC_SWAY_SPD_Y           2082
#define IDC_STATIC_TITLE_SWAY_ZERO      2083
#define IDC_SCROLLBAR_IMAGE_H           2084
#define IDC_SCROLLBAR_IMAGE_V           2085
#define IDC_STATIC_SWAY_ZERO_X          2086
#define IDC_STATIC_SWAY_ZERO_Y          2087
#define IDC_CHECK_IMAGE_SCALE           2088
#define IDC_STATIC_TILT_SPD_DEG_Y       2089
#define IDC_CHECK_TARGET_ROI_1          2090
#define IDC_CHECK_TARGET_POS_1          2091
#define IDC_CHECK_TARGET_CONTOURS_1     2092
#define IDC_CHECK_TARGET_ROI_2          2093
#define IDC_CHECK_TARGET_POS_2          2094
#define IDC_CHECK_CAMERA_EXPOSURE       2095
#define IDC_CHECK_TARGET_LEN            2096
#define IDC_CHECK_TARGET_CONTOURS_2     2097
#define IDC_STATIC_TITLE_IMAGE_MASK     2098
#define IDC_STATIC_TITLE_TARGET_LEN     2099
#define IDC_BUTTON_TASK_ITEM1           2100
#define IDC_STATIC_TILT_SPD_RAD_X       2100
#define IDC_BUTTON_TASK_ITEM2           2101
#define IDC_CHECK_SWAY_POS              2101
#define IDC_BUTTON_TASK_ITEM3           2102
#define IDC_STATIC_TILT_SPD_RAD_Y       2102
#define IDC_BUTTON_TASK_ITEM4           2103
#define IDC_BUTTON_TASK_ITEM5           2104
#define IDC_BUTTON_TASK_ITEM6           2105
#define IDC_CHECK4                      2109
#define IDC_BUTTON_CURSOR_L             2228
#define IDC_BUTTON_CURSOR_R             2232
#define IDC_BUTTON_CURSOR_U             2233
#define IDC_BUTTON_CURSOR_D             2234
#define IDC_BUTTON_IMAGE_SAVE           2241
#define IDC_STATIC_BMP_IMAGE            2245
#define IDC_STATIC_BMP_TARGET_2         2247
#define IDC_STATIC_BMP_SWAY_POS         2248
#define IDC_STATIC_BMP_TARGET_1         2249
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
